# Generated by Django 3.2.25 on 2024-04-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sustainability_score', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('city_name', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('googleId', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sustainability_score', models.FloatField()),
                ('flight_duration', models.CharField(max_length=255)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='extension.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches_dest', to='extension.place')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches_origin', to='extension.place')),
            ],
        ),
    ]
