# Generated by Django 5.0.4 on 2024-04-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='airline',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='googleId',
            new_name='googleid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
    ]
