# Generated by Django 5.0.4 on 2024-04-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='user_id',
            new_name='user',
        ),
    ]
