# Generated by Django 5.0.4 on 2024-04-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_remove_search_airline_rename_googleid_user_googleid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
