# Generated by Django 5.0.4 on 2024-04-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0003_place_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='search',
            name='origin',
        ),
        migrations.AddField(
            model_name='search',
            name='destination_code',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='origin_code',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
