# Generated by Django 5.0.4 on 2024-04-07 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0003_rename_user_id_search_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='search',
            name='departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='search',
            name='timestamp_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
