# Generated by Django 5.0.4 on 2024-04-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0004_search_arrival_date_search_departure_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='flight_duration',
        ),
    ]
