# Generated by Django 5.0.4 on 2024-04-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0005_remove_search_flight_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
